### PR TITLE
Fix Empty Image Filenames in CSV

### LINKED ISSUE #1173: Handle Empty Image Names (Column 2)  in VIAME CSV Import
**Describe the bug**
When importing a CSV for an image-sequence where there are no filenames specified in column 2 in the viame csv.  It will error and say that the images are missing from the annotation.

**To Reproduce**
1. Take a working viame CSV for import and delete the values in Column 2 so they are empty.
2. Try to import or load it into the system.

**Expected behavior**
Image ordering is no longer required so it should use the default image sort ordering and not have an error.

### PR DESCRIPTION
**Pull request by BryonLewis**
fixes #1173 

- Adds a check to see if the field is empty when using the image map.  It will skip using the image map if the field is empty.  
- Added another check to make sure that there are no files where it swaps between providing image filenames and not.  This needed to handle both cases of (first row empty, second row populated) and (first row populated, second row empty).  So it will throw an error when it encounters a row which is different than the previous rows.

Note:  I wanted to add tests but the rejection process within the `viame.ts` `parse` function wasn't working well using jest.  I may need to look into this more to figure out how I can add some relevant tests for image ordering and this new error.

### CODE REVIEW

File: client/platform/desktop/backend/serializers/viame.ts [hunk 1]
```diff
@@ -258,15 +258,21 @@ async function parse(input: Readable, imageMap?: Map<string, number>): Promise<A
     });
     parser.on('readable', () => {
       let record: string[];
+      let hasFilenames;
```
Comment (subdavis) [inline client/platform/desktop/backend/serializers/viame.ts:261]: This variable is named like a boolean variable, but it's not boolean.  It's true/false/undefined.  Please declare its type here so TS can enforce assignment.

**Review by subdavis — CHANGES_REQUESTED** [review]
Nit: declare type named variable
