### PR TITLE
Desktop Fixes

### LINKED ISSUE #924: [FEATURE] Refresh or refresh pop-up when desktop pipes finished running
When running a pipeline from within the annotator it's confusing to know when a processing run is finished

### LINKED ISSUE #937: [BUG] Read Only Mode is broken
**Describe the bug**

On desktop, read-only mode no longer works

**To Reproduce**
1. Enable RO mode and save
2. Launch a dataset
4. Save button still works?

### LINKED ISSUE #939: [BUG] DIVE-Desktop selects detection not track file when both produced
In the latest version of DIVE desktop in VIAME if a computed_detections.csv and computed_tracks.csv were both produced by a .pipe then computed_detections is displayed but computed_tracks should take priority

### LINKED ISSUE #940: [FEATURE] DIVE-Desktop in jobs panel option to open up results in annotation
In web on the jobs panel you can directly go from the jobs list to the annotation viewer for a sequence, though not desktop

### PR DESCRIPTION
**Pull request by BryonLewis**
fixes #939 
Was fixed by swapping the order of the `detectorOutput, trackOutput` in the `processOtherAnnotationFiles` to cause it to load them in sequence where if the `trackOutput` exists it is the final result.

fixes #937
Simple fix with a text error on the attribute.  Swapped `read-only-mode` to  `readonly-mode`

fixes #924 
In the `ViewerLoader.vue` placed a watcher on the jobs queue.  Will check to see if a job with which contains the same ID as the currently loaded one if it has completed successfully and if the jobType is a pipeline.  If all those conditions are met it will prompt the user telling that it is complete and if they want to reload the annotation.  Then it calls the standard reloadAnnotation function used for stereo and importing.
image

fixes #940 
Changed the list in the jobs panel to include links to the datasets used in the job.  Currently there was a list of jobIds that represented datasets being used.  Clicking on them now will take the user to that dataset and open it up.
image

### CODE REVIEW

File: client/platform/desktop/frontend/components/ViewerLoader.vue [hunk 1]
```diff
@@ -38,11 +43,29 @@ export default defineComponent({
...
   setup(props) {
+    const { prompt } = usePrompt();
     const viewerRef = ref();
     const compoundId = ref(props.id);
     const subTypeList = computed(() => [datasets.value[props.id]?.subType || null]);
     const readonlyMode = computed(() => settings.value?.readonlyMode || false);
 
+    watch(runningJobs, async (_previous, current) => {
+      const index = current.findIndex((item) => item.job.datasetIds.includes(props.id));
+      if (index !== -1 && current[index] && current[index].job.exitCode !== -1 && current[index].job.jobType === 'pipeline') {
```
Comment (subdavis) [inline client/platform/desktop/frontend/components/ViewerLoader.vue:54]: Use `find` instead of `findIndex` if you don't actually care about the index and you just want the job.  It will make the conditional on 54 less involved.

```
      const job = current.find((item) => item.job.datasetIds.includes(props.id));
      if (job && job.job.jobType === 'pipeline' && job.job.exitCode !== -1) {
```

**Review by subdavis — CHANGES_REQUESTED** [review]
Switch to `find`, and the other comment is more of a gotcha

**Review by subdavis — APPROVED** [review]
