### PR TITLE
Insert bugFix 

### LINKED ISSUE #731: [BUG] Splitting doesn't save properly.
**Describe the bug**
If you split data and save the data the upsert/delete doesn't update proper for the items included.

**To Reproduce**
1. Go to any dataset with tracks
2. Click on someplace within a track and split it.  Note that you delete your current track and get two new ones. 
3. Check the markchanges pending you only have one action when you should have 3 (1 delete and 2 inserts)
4. Record the network tab to see that the delete is propagated but the upsert isn't
5. You can also reload the data if it is small enough and notice that you now have 2 tracks missing

**Expected behavior**
Splitting should cause 3 updates

### PR DESCRIPTION
**Pull request by BryonLewis**
Fixes #731 

Issue with saving after splitting tracks.

### CODE REVIEW

File: client/src/use/useTrackStore.ts [hunk 1]
```diff
@@ -75,17 +80,20 @@ export default function useTrackStore({ markChangesPending }: UseTrackStoreParam
...
-    if (afterId) {
+    if (args && args.afterId) {
       /* Insert specifically after another trackId */
-      const insertIndex = trackIds.value.indexOf(afterId) + 1;
+      const insertIndex = trackIds.value.indexOf(args.afterId) + 1;
       trackIds.value.splice(insertIndex, 0, track.trackId);
     } else {
       trackIds.value.push(track.trackId);
     }
+    if (!args || !args.imported) {
```
Comment (subdavis) [inline client/src/use/useTrackStore.ts:94]: Maybe this reads better?

```suggestion
    if (!args?.imported) {
```

**Review by subdavis — APPROVED** [review]
Good catch, thanks.

**Review by subdavis — APPROVED** [review]
