### PR TITLE
import fix and some animation for importing

### LINKED ISSUE #871: [BUG] New dataset annotaiton import button ignores value
**Describe the bug**
Desktop bug import doesn't respect of chosen annotation file.

**To Reproduce**
1. import a dataset
2. select a different file than the suggested file, or just clear the value of the suggestion
3. see desktop ignore this option and load the suggestion anyway on import.

### LINKED ISSUE #873: [BUG] import button from viewer shows no loading progress, seems to freeze.
Make it show some kind of progress indicator.

### PR DESCRIPTION
**Pull request by BryonLewis**
Fixes #871 
Fixes #873 

871 - upated `_importTrackFile` so that it can accept a duser defined track file.  If that track file is not included it will fall back to the default operation (This is required for stereo import of folders).  If it is included and set to null/empty it will create an empty dataset.

873 - added a disabled state and spinner to the import for longer uploads.  The previous delays were actually caused by the clearing of the tracks and not the import process itself.  If modified the clearAllTracks function to remove the objects instead of iteratively calling `removeTrack`.  This sped it up so on desktop it should be relatively quick and the longest part will be reloading the data.

### CODE REVIEW

**Comment by BryonLewis** [comment]
Updated to swap the `clearAllTracks` to clear the `trackMap`, `trackIds` then iterate through and remove all elements from the `intervalTree`.  The other option for the interval tree is changing it to a `let` instead of `const` but I don't really feel great about doing that for something that is passed around.

This updated version handles the swapping between large imports much better.  The majority of the time is spent loading instead of removing the older tracks.

**Review by subdavis — CHANGES_REQUESTED** [review]
* I think the "Anntation File" input should be outlined and have the same padding as the other parts of the dialog.  It doesn't align vertially
* It's not dismissable, so I can't, for example, import a dataset without annotations if one exists in the folder.  I should be able to override to make it empty.
 
Screenshot from 2021-08-03 14-25-18

**Comment by BryonLewis** [comment]
Dismissable, prepend-icon-inner and small update to allow removal of annotation file if wanted.
image

File: client/platform/desktop/backend/native/common.ts [hunk 1]
```diff
@@ -816,45 +816,47 @@ async function _importTrackFile(
...
   /* Look for JSON track file as first priority */
   let foundDetections = false;
-  const foundTrackFileAbsPath = await _findJsonTrackFile(jsonMeta.originalBasePath);
-  const trackFileAbsPath = userTrackFileAbsPath !== undefined
-    ? userTrackFileAbsPath : foundTrackFileAbsPath;
-  if (trackFileAbsPath !== null && !CsvFileName.test(trackFileAbsPath)) {
+  if (userTrackFileAbsPath !== null) {
+    const foundTrackFileAbsPath = await _findJsonTrackFile(jsonMeta.originalBasePath);
+    const trackFileAbsPath = userTrackFileAbsPath !== undefined
+      ? userTrackFileAbsPath : foundTrackFileAbsPath;
```
Comment (subdavis) [inline client/platform/desktop/backend/native/common.ts:822]: `userTrackFileAbsPath` is annotated in the stub as `string | null` and then compared to `undefined` inside a conditional block where it's already been established as `not null`.  

I'm going to venture a guess that you probably don't need to call `_findJsonTrackFile` at all in this function because it was called already in the pre-import step.  

I'm going to venture a guess that because `foundDetections` requires `trackFileAbsPath` requires `userTrackFileAbsPath` which is always set inside the new conditional you added, that variable is doing no work at all and the block inside `Look for other types of annotation files as a second priority` is now unreachable code.  Is that right?

**Review by subdavis — CHANGES_REQUESTED** [review]

File: client/platform/desktop/backend/native/common.ts (hunk 1 above)
Comment (subdavis) [reply client/platform/desktop/backend/native/common.ts:822]: Yeah, I think we need to get rid of the test on line 823 for `trackFileAbsPath` so it's just "If it's a json file do this, otherwise if it's a CSV file do this".

The comment about look ing for other types of annotation files is misleading.  there should no longer be any file discover going on in this function.  It's just handling the value of `userTrackFileAbsPath`

Comment (BryonLewis) [reply client/platform/desktop/backend/native/common.ts:822]: For the case of not importing stereoscopic data that is correct.  In stereoscopic there is no precursor to finding the track files for each camera.  That should probably be done as another PR where you define the folder and assign track files for each camera if needed.  
If you import stereoscopic right now `userTrackFileAbsPath` is `undefined` and it should look for other annotation files associated with each camera.  It does import those relative files but right now the display doesn't show them.  Maybe this update should be apart of my stereoscopic viewing update.

Comment (subdavis) [reply client/platform/desktop/backend/native/common.ts:822]: I see, thanks.

**Review by subdavis — APPROVED** [review]
