### PR TITLE
Grouped minor fixes

### LINKED ISSUE #728: [FEATURE] Toggle Keyframe hotkey
user request.

Hotkey to toggle keyframe both inside and outside a track bounds where the outer bound keyframe has interpolation on.

When annotating certain targets, it's nice to periodically drop a keyframe without adjusting the bounding box as a checkpoint.  This is helpful for targets that don't  move for a while then move.

### LINKED ISSUE #762: [BUG] Possible race condition when multiple saves are in-flight.
**Describe the bug**
Possible race condition when saving detections

**To Reproduce**
* spam click the save button.

**Expected behavior**
Save button should be disabled during an in-progress save.

### LINKED ISSUE #765: [BUG] PayloadTooLargeError
**Describe the bug**
When you try to save a large number of changes, like deleting all 20K tracks.

**To Reproduce**
1. Load a huge dataset on desktop
2. Mass delete

**Additional context**

```
PayloadTooLargeError: request entity too large
    at u (/tmp/.mount_DIVE-DA9xHB8/resources/app.asar/background.js:2:903291)
    at e.exports (/tmp/.mount_DIVE-DA9xHB8/resources/app.asar/background.js:2:903038)
    at e.exports (/tmp/.mount_DIVE-DA9xHB8/resources/app.asar/background.js:2:177991)
    at /tmp/.mount_DIVE-DA9xHB8/resources/app.asar/background.js:2:895149
    at s.handle_request (/tmp/.mount_DIVE-DA9xHB8/resources/app.asar/background.js:2:390176)
    at /tmp/.mount_DIVE-DA9xHB8/resources/app.asar/background.js:2:384662
    at /tmp/.mount_DIVE-DA9xHB8/resources/app.asar/background.js:2:384684
    at Function.h.process_params (/tmp/.mount_DIVE-DA9xHB8/resources/app.asar/background.js:2:385193)
    at y (/tmp/.mount_DIVE-DA9xHB8/resources/app.asar/background.js:2:384233)
    at /tmp/.mount_DIVE-DA9xHB8/resources/app.asar/background.js:2:1168892

```

### PR DESCRIPTION
**Pull request by BryonLewis**
Some minor bugfixes
Fixes #762 - disabling button while save is in progress
Fixes #765 - expressJS setting of JSON limit to 250MB from the default of 100KB
Fixes #728 :  
- Added in 'K' for toggle keyframe as well as updated the shortcuts in the help for split/merge/keyframe.
- Modified v-mousetrap to hidden div only visible when the item is selected.  Before the shift+enter focus call was added and called on all visible items in the virtual scroll list.  This will limit it to only the selected one having keyboard shortcuts applied.
- Keyframes should be added and removed while in edit mode by pressing K
- Added in toggle interpolation shortcut "I"
- "Enter" no longer went to first frame, modified for "Home" or "End" going to the first/last frame of the currently selected track
- Updated the keyboard control list to reflect the update keyboard commands and reordered it to fit better.

### CODE REVIEW

File: client/src/components/TrackItem.vue [hunk 1]
```diff
@@ -146,7 +146,21 @@ export default defineComponent({
...
+          interFeature = f.lower;
+        }
+        if (interFeature) {
+          props.track.setFeature({
+            ...interFeature,
+            frame: frameRef.value,
+            keyframe: true,
+          });
+        }
+      } else if (f.isKeyframe) {
```
Comment (subdavis) [inline client/src/components/TrackItem.vue:163]: Would it be unreasonable to ask that `toggleKeyframe(frame: number)` be made an instance method in `track.ts`?

It's much easier to test there than it would be here.  You don't need to add tests.

File: client/src/components/TrackList.vue [hunk 2]
```diff
@@ -55,7 +55,7 @@ export default defineComponent({
 
   components: { TrackItem },
 
-  setup(props) {
+  setup(props, { emit }) {
```
Comment (subdavis) [inline client/src/components/TrackList.vue:58]: Unused?

**Review by subdavis — CHANGES_REQUESTED** [review]
Minor comment.

File: client/src/components/TrackList.vue (hunk 2 above)
Comment (BryonLewis) [reply client/src/components/TrackList.vue:58]: yup thanks, I was going to place the Home/End call in the `TrackList` until I decided it made more sense to update how `TrackItem.vue` uses the v-mousetrap to prevent all the excess calls and binding on each item.

File: client/src/components/TrackItem.vue (hunk 1 above)
Comment (BryonLewis) [reply client/src/components/TrackItem.vue:163]: That's a great idea.  I'll do that and I'll add tests.  It feels kind of weird having that kind of logic/function live in a Vue component.  I think I still need to keep the computed `feature` for some stuff in the template though.

**Review by subdavis — APPROVED** [review]
