### PR TITLE
Fix #1052 import json and meta json

### LINKED ISSUE #1052: [BUG] Annotation and config import in desktop not working.
**Describe the bug**
JSON files cannot be imported properly on desktop

### PR DESCRIPTION
**Pull request by subdavis**
## Changes

* Fixes bug where every json file was being parsed as a NIST file and failing.
* Adds feature to import meta json on desktop for parity with web.

## Notes

* Removes 2 large blocks of code that were inline-copies of other existing functions.
* Replace `annotationImport` with `dataFileImport` agnostic to the kind of data being ingested to match web logic
* Add tests.

## Testing

Tested with json tracks, meta files, and CSV.  I don't have any NIST data, but if you tell me where to find some, I can check that too.

fixes #1052

### CODE REVIEW

File: client/platform/desktop/backend/native/common.ts [hunk 1]
```diff
@@ -545,41 +546,53 @@ async function saveAttributes(settings: Settings, datasetId: string, args: SaveA
...
+  let tracks: TrackData[] | null = null;
+  const meta: DatasetMetaMutable & { fps?: number } = {};
+  if (JsonFileName.test(path)) {
+    const jsonObject = await _loadAsJson(path);
+    if (nistSerializers.confirmNistFormat(jsonObject)) {
+      // NIST json file
+      const data = await nistSerializers.loadNistFile(path);
+      tracks = data.tracks;
+      meta.fps = data.fps;
+    } else if (DatasetMetaMutableKeys.some((key) => key in jsonObject)) {
```
Comment (BryonLewis) [inline client/platform/desktop/backend/native/common.ts:574]: We need to restrict to only the `DatasetMetaMutableKeys`.  If you do a full export from the server you get a `meta.json` file.  If you import that file it passes this check but then merges with the existing meta structure causing the file to have a bunch of extra fields which may be incorrect if there is any overlap (like `fps` and `type` fields).  This could also occur if a user tries to import their meta.json desktop file from another or similar dataset.  It will do the merge and completely break the data then.

**Review by BryonLewis — CHANGES_REQUESTED** [review]
This cleans up quite a bit of stuff.
One change noted is there was previously a guard to only allow NIST import on video files.  This was done because the core NIST format relies specifically on named video files and frame numbers.  I don't think this needs to be added back in.

The important issue is the possible clobbering of the project `meta.json` file by doing a merge with a full export `meta.json` from the server.  If you export the configuration file and use it that works perfectly.  If you do a full zip export and use the meta.json that is where there are possible failures.

File: client/platform/desktop/backend/native/common.ts (hunk 1 above)
Comment (subdavis) [reply client/platform/desktop/backend/native/common.ts:577]: * Broken test case added in 06a7815
* Test fixed in 98d159f

**Review by BryonLewis — APPROVED** [review]
:+1:
